---
title: "Statistical Tools for Large-Scale Spatiotemporal Transportation Data"
author: "Marie Hardt"
date: "2025-10-09"
institute: "Iowa State University"
format: 
  revealjs:
    theme: simple
---

# Spatiotemporal Transportation Data

## Vehicle Trajectory Data

* Collected from vehicles as they are driven.

* Points observed regularly (e.g., every 1-3 sec. for our data sources).

## Typical Variables

* Location (latitude/longitude).
  
* Speed.
  
* Heading.

* Etc.

## Sources

* Naturalistic driving studies (NDS)

  - Instrumentation installed in study participants' vehicles.

* Connected vehicles

  - Instrumentation built into the vehicle by original manufacturer.

## Use Cases

* Studying driving behavior.

* Driving maneuver detection.

* Work zone impact/performance.

* Etc.

# GPS Data

## Units Are Important!

It's 25 degrees outside today.

* Fahrenheit: 🥶

* Celsius: 😎

## Coordinate Reference System

* Describes how latitude/longitude coordinates relate to real places on the Earth's surface.

* Ensures locations are properly located because they are related to the correct ellipsoidal approximation of the Earth.

* CRS for GPS data: WGS 84.

## Projected Coordinate System

* Projects coordinates from the Earth's surface (3-D) down to 2 dimensions.

* 3-D surfaces can't be projected down to 2 dimensions without distortion (but that's okay).

* Example: WGS 84 Web Mercator projection for coordinates using the WGS 84 projection.

## GPS Overview (Simplified)

* Part of Global Navigation Satellite System (GNSS).

* Satellite constellation orbits the Earth.

* Ground-based monitoring stations track satellites and transmit satellite locations back to the satellites.

* Satellites transmit their positions to receivers.

* Receivers determine the travel time of the signal from the satellite and thus the distance to the satellite. 

## Satellite Geometry

## Dilution of Precision

* Measure of GPS data quality

* Different types

## Issues

* Poor GPS signal

* Low DOP doesn't always mean good quality GPS data

* Etc.

# Map Matching

## Main Questions

1. Which road segment is the vehicle using?

2. Where exactly on the road segment is the vehicle?

## Existing Map Matching Methods

* Naive methods

* More advanced naive methods

* Hidden Markov models

* Etc.

## Map Matching Challenges

* True path is usually unknown

* Error quantification

* Outlier sensitivity

* Etc.

# Areas of Interest

## Visualizing Telematics Data

* Relating location in time and space to other variables 

* R package `DrivePlotR`

## Processing Telematics Data

* Map matching

* Correctly locating telematics data in space (latitude/longitude on correct part of the road system) and time

## Drawing Insights from Telematics Data

For example,

* Developing driving biomarkers for age-related cognitive decline in senior citizens

* Deriving the time to complete turning maneuvers at intersections

* Quantifying the influence of work zones, crashes, etc. on traffic flow

## References


