---
title: "Brief Article Summaries"
format: html
bibliography: "`r rbbt::bbt_write_bib('references.bib', overwrite = TRUE, library_id=rbbt::bbt_library_id('Graphics Research'), translator='bibtex')`"
---

```{r}
#| echo = F
library(rbbt)
```

# Goal: Find Associations Between Mild Cognitive Impairment and Driving Behavior in Older Adults

General note: a lot of these articles come from a group at the Washington University Knight Alzheimer’s Disease Research Center

* @bayatGPSDrivingDigital2021: "GPS driving: a digital biomarker for preclinical Alzheimer disease"

  - When included as features in a random forest model, driving behaviors such as the average number of jerks and the number of trips made at night can be used to predict preclinical Alzheimer's disease in 139 adults from the St. Louis, Missouri, metropolitan area who were age 65 or older and had normal cognition at the time of study enrollment.
  
* @bayatDrivingAssessmentPreclinical2022: "Driving assessment in preclinical Alzheimer's disease: progress to date and the path forward"

  - Preclinical AD: people have evidence of AD pathology but no clinical symptoms
  
* @davisEvaluationNaturalisticDriving2020: "Evaluation of naturalistic driving behavior using in-vehicle monitoring technology in preclinical and early Alzheimer's disease"

  - For a convenience sample of older drivers with symptomatic AD, older drivers with preclinical AD, and cognitively normal older drivers whose driving was monitored with GPS data logging (all participants) and video recording (participants with symptomatic AD) for 3 months, Spearman correlations ($\rho$) showed a strong association between speeding and collisions/near collisions in the symptomatic AD participants. In a Poisson regression model, performance on a psychomotor task (Trails A) was a significant predictor of the number of adverse driving events (hard braking, sudden acceleration, and speeding).
  
* Articles that mention self-regulatory driving behavior for older drivers with preclinical AD:

  - @bayatDrivingAssessmentPreclinical2022: "Driving assessment in preclinical Alzheimer’s disease: progress to date and the path forward"
  
    + Study participants: this article is a review of previous studies, so there were no direct study participants
  
    + Older adults with preclinical AD are less likely to drive and tend to be less aggressive drivers (fewer incidences of hard braking, speeding, and sudden acceleration).
  
  - @davisEvaluationNaturalisticDriving2020: "Evaluation of Naturalistic Driving Behavior Using In-Vehicle Monitoring Technology in Preclinical and Early Alzheimer’s Disease
  
    + Study participants: convenience sample including 11 drivers aged 60 or older with symptomatic AD and 22 cognitively normal drivers aged 65 or older (11 amyloid-negative participants and 11 participants with evidence of amyloid; beta-amyloid is the "primary driver and earliest marker of AD pathogenesis and cascade")
  
    + During the early stages of AD (when cognitive function is stil unaffected), people might experience a period of self-regulatory behavior to prevent aggressive driving behavior.
    
    + As cognitive function declines as AD progresses, self-regulatory driving behavior decreases.
  
  - @babulalNaturalisticStudyDriving2019: "A Naturalistic Study of Driving Behavior in Older Adults and Preclinical Alzheimer Disease: A Pilot Study"
  
    + Study participants: 20 cognitively normal adults aged 65 or older (10 participants with preclinical AD and 10 participants without preclinical AD)
  
    + Participants with preclinical AD drove fewer trips than participants without preclinical AD, but participants with preclinical AD drove more miles per trip.
    
    + Could study participants with preclinical AD drive more miles per trip because they have trouble with navigation and get lost?
    
    + Study participants with preclinical AD drove less at night and had fewer trips with aggressive driving behaviors.
    
* @camilleriDrivingAssessmentPersons2023 "Driving Assessment for Persons with Dementia: How and when?"

  - Driving cessation in older adults is associated with a decrease in their quality of life.
  
  - "Dementia is a cause of cognitive impairment but not all cases of cognitive impairment are due to dementia."
  
  - This article is a review of previous studies, so it might be useful for me to look at some of the previous studies as well.
  
  - Do advanced driver-assistance systems act as strategies to help drivers compensate for cognitive impairment?
  
* @aschenbrennerNeuropsychologicalCorrelatesChanges2022 "Neuropsychological Correlates of Changes in Driving Behavior Among Clinically Healthy Older Adults"

  - Study participants: 161 participants in longitudinal studies of memory and aging at the Knight Alzheimer Disease Research Center (ADRC) at Washington University in St. Louis who were cognitively normal, at least 65 years old, and had 1 year of driving data available
  
  - Similar driving features to @bayatGPSDrivingDigital2021 (this paper and @bayatGPSDrivingDigital2021 share some authors)
  
  - Driving space composite includes:
    
    + Total number of trips
    
    + Radius of gyration (typical distance a person travels)
    
    + Distance traveled
    
    + Number of night trips
    
    + Number of days traveled
    
    + Number of unique locations
    
  - Driving performance composite includes:
  
    + Overspeeding proportion
    
    + Hard braking proportion
    
    + Sudden acceleration proportion
  
  - Trip: ignition start to ignition off
  
  - Only analyzed data from before March 2020
  
  - Statistical analyses in `lme4` R package
  
  - "Attentional control is a key moderator of change over time in driving space but not driving performance in older adults."  (attentional control is "the ability to focus on the relevant aspects of the environment and ignore distracting or competing information")
  
* @roe5YearLongitudinalAssessment2019: "A 2.5-Year Longitudinal Assessment of Naturalistic Driving in Preclinical Alzheimer’s Disease"
  
  - Study participants: 20 cognitively normal individuals (10 of whom had preclinical AD and 10 of whom did not) age 65 or older recruited from longitudinal studies at the Washington University Knight Alzheimer’s Disease Research Center
  
  - DRIVES data loggers installed in participants' vehicles
  
  - Data collection period: July 1, 2015, to January 30, 2018 (one participant passed away around a year after data collection began)
  
  - Data from the data logger were aggregated by month; all participants followed for 2.5 years have 30 data points for all variables collected by the data logger
  
  - Statistical analyses: linear mixed models in SAS
  
  - Presence of baseline differences between participants was determined based on y-intercepts for linear mixed models
  
  - In general, the linear mixed models showed little difference in changes in logitudinal driving behavior between the study participants with and without preclinical AD.
  
  - Research shows that changes in sensory and motor function happen in the preclinical stage of AD before cognitive decline is noticeable.
  
* @murphyCognitiveBrainReserve2022: "Cognitive and brain reserve predict decline in adverse driving behaviors among cognitively normal older adults" 

  - Study participants: 186 cognitively normal adults aged 65 or older recruited from longitudinal studies at the Washington University Knight Alzheimer’s Disease Research Center who had MRI data, neuropsychological testing data, and at least one year of driving activity measured by the DRIVES system prior to March 2020
  
  -*Cognitive reserve (CR): "the brain's adaptability or functional robustness despite damage;" breadth of memory or thinking abilities
  
  - Brain reserve (BR): "physical and neuroanatomical structures of the brain"
  
  - Conceptualization: CR is the brain's software while BR is the brain's hardware.
  
  - Study investigated
  
    + The relationship between CR (measured using a reading fluency task) and longitudinal driving behaviors (measured using a DRIVES data logger)
    
    + The relationship between daily driving and BR (measured using MRI)
    
  - Used a linear mixed model to predict the mean rate of change in driving outcomes after accounting for age, education, and gender
  
    + Have the separate regression line (y-intercept and slope) for each participant
    
    + y-intercepts for regressions with driving variables represent baseline
    
  - Analyses performed in SAS
  
  - "Those with lower BR and CR are more likely to restrict their driving behavior and adapt their daily behaviors such as trips made during the day, speeding, and hard braking as time progresses."
  
* @herrmannPredictorsDrivingCessation2006: "Predictors of driving cessation in mild-to-moderate dementia"

  - *Canadian Outcomes Study in Dementia (COSID)*

  - *Study participants: 883 patients with mild-to-moderate dementia from 32 centers across Canada (British Columbia, the Prairie provinces, Ontario, Quebec, and the Atlantic provinces) who were age 60 or older and living in the community*
  
  - *Information and assessments conducted from the start of the study (baseline) and every 6 months for 3 years or until death*
  
  - *Assessment types:*

    + *Cognition by way of the Modified Mini-Mental State Examination (3MS)*  
    
    + *Global staging/severity (GDS)*
    
    + *Function by way of the Functional Autonomy Measurement System (SMAF)*
    
    + *Behavior by way of the Neuropsychiatric Inventory (NPI)*
    
  - *Statistical analyses:*
    
    + *Exploratory Cox survival analysis (event of interest was driving cessation)*
    
    + *Cox regression analysis*
    
  - *Cognitive impairment and behavioral disturbances were strong predictors of driving cessation.*

  - *No naturalistic driving component to this study*
  
  