---
title: "Timeline to PhD Completion"
author: "Marie Hardt"
format: 
  pdf:
    geometry:
      - top=1in
      - bottom=1in
      - left=1in
      - right=1in
---

# Proposed Dissertation Chapter Outlines

## Title: Statistical Tools for Large-Scale Spatio-Temporal Transportation Data

## Chapter 0: Literature Review & Problem Statement

This chapter presents an overview of the data sources used in this project and the challenges uncovered in their use. Spatio-temporal transportation data are discussed, and an overview of GPS and related quality measures are presented. Prior work on the map-matching problem is discussed. The new contributions of the work are explained.

## Chapter 1: Software Tools for Large-Scale Spatiotemporal Transportation Data

This chapter discusses software tools developed for visualizing large-scale spatio-temporal transportation data (including my R package `DrivePlotR`) and explains how insights based on the visualizations led to subsequent work.

## Chapter 2: Detecting Driving Behavior from Large-Scale Spatiotemporal Transportation Data

This chapter explains how driving behavior may be detected from telematics data. An application to cognitive health in older drivers is presented. (This chapter will include the paper "Turns and Downturns in Aging Drivers.")

## Chapter 3: Determining Precise Vehicle Locations on the Road System

This chapter covers a new linkage-based method for determining a vehicle's location on a road segment after a map-matching algorithm is used. An application using this linkage method is discussed.

<!-- ## Related Presentation: `DrivePlotR` at the Transportation Research Board (TRB) Annual Meeting in January 2026 -->

# Timeline

## November 2025

* Submit a revision of the `DrivePlotR` paper to appear in the TRB Annual Meeting online program: November 20, 2025. (Done on November 20, 2025)

* Update Chapter 0 (Literature Review & Problem Statement) of my dissertation: November 30, 2025. (Done)

## December 2025

* Submit my TRB poster about `DrivePlotR` for review by co-authors: December 2, 2025. (Done)

* Address co-author comments on my `DrivePlotR` poster as necessary. (Done)

* Submit my TRB poster to appear in the conference program: December 19, 2025. (Done on December 13, 2025)

* Synthesize ideas for my map-matching position determination method and begin programming an implementation of the method: December 31, 2025.

* Update Chapter 0 of my dissertation: December 31, 2025.

## January 2026

* Present my poster about `DrivePlotR` at the TRB Annual Meeting: January 13, 2026.

* Submit an updated draft of "Turns and Downturns in Aging Drivers" to co-authors: January 31, 2026.

* Continue the initial implementation of my map-matching position determination method and start testing it: January 31, 2026.

* Update Chapter 0 of my dissertation: January 31, 2026.

## February 2026

* Address co-author comments about "Turns and Downturns in Aging Drivers" as necessary.

* Submit an improved draft of the `DrivePlotR` paper to co-authors after addressing any comments/feedback received after my TRB presentation: February 3, 2026.

* Choose an application for my map-matching position determination method and start writing a paper about it: February 13, 2026.

* Submit "Turns and Downturns in Aging Drivers" to a peer-reviewed journal: February 27, 2026.

* Update Chapter 0 of my dissertation: February 28, 2026.

* Continue testing and updating my map-matching position determination method in the context of the application: February 28, 2026.

## March 2026

* Address co-author comments on the `DrivePlotR` paper as necessary: March 13, 2026.

* Address peer-review comments on "Turns and Downturns in Aging Drivers" as necessary.

* Use my map-matching position determination method in the context of the application and continue writing the paper about it: March 31, 2026.

* Update Chapter 0 of my dissertation: March 31, 2026.

## April 2026

* Submit a draft of the `DrivePlotR` paper to a peer-reviewed journal: April 10, 2026.

* Address peer-review comments about submitted papers as necessary.

* Further refine my map-matching position determination method and continue writing the paper about it: April 30, 2026.

* Update Chapter 0 of my dissertation: April 30, 2026.

## May 2026

* Further refine my map-matching position determination method and continue writing the paper about it: May 31, 2026.

* Address peer-review comments about submitted papers as necessary.

* Update Chapter 0 of my dissertation: May 31, 2026.

## June 2026

* Submit a draft of the paper about my map-matching position determination method to co-authors: June 30, 2026.

* Address peer-review comments about submitted papers as necessary.

* Finish Chapter 0 of my dissertation: June 30, 2026.

## July 2026

* Submit my dissertation to my committee by July 3, 2026.

* Defend my dissertation by July 17, 2026.

* Submit Graduate Student Approval Form: July 21, 2026.

* Address committee comments and submit my dissertation to the Graduate College: July 23, 2026.

* Submit a draft of the paper about my map-matching position determination method to a peer-reviewed journal: July 24, 2026.

* Address peer-review comments about submitted papers as necessary.





















